### ISSUE TITLE
Cannot find module 'bufferutil'

### ISSUE THREAD

**Issue by jantielens** [bitfinexcom/bitfinex-api-node#119]
I'm trying to get the WS API working on Windows 10 with Node 8.4.0 installed. Steps:
- create new node app
- npm install bitfinex-api-node --save
- write some basic code (using the websocket api)

Basic stuff, like getting ticker info works fine. But when I try to create an order, nothing happens (no error, no success, ...). When debugging the app (using VS Code, catching every exception) I can detect the following error:

```
Error: Cannot find module 'bufferutil'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (c:\node\bitfinexwstest3\node_modules\ws\lib\BufferUtil.js:35:22)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
```

FYI: even when only using the ticker events, I can detect the error, but the code still seems to work.

Any ideas?

**Comment by jantielens** [comment]
Just discovered #117, maybe the exception is not breaking anything (because it's caught internally).

**Comment by robertkowalski** [comment]
hi @jantielens,

the error happens in the dependency bufferutil (https://github.com/websockets/bufferutil) which is a native c++ extension. it looks like it wasn't compiled properly.

 - i'm not a windows expert, do you have the c++ toolchain installed? 
- when you remove the node modules folder and reinstall the dependencies, do you see a compile error in the log?
 - maybe this can help you as well? https://github.com/nodejs/node-gyp/issues/629

have a great new week,
robert

**Comment by robertkowalski** [comment]
closing, abandoned issue
